env:
  browser: true
  es6: true
extends: semistandard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: warn
  no-unused-vars:
    - warn
    - args: after-used
  import/no-default-export: error